### ISSUE TITLE
请给一下训练的模型，谢谢。！

### ISSUE THREAD

**Issue by Char-Manage** [Dustsorrow/yolov5-Fall-Down-Detection#7]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

请给一下训练的模型，谢谢。！

**Comment by Dustsorrow** [comment]
刚刚上传了我的训练模型
